---
version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    hostname: elasticsearch
    restart: always
    ports:
      - 9200:9200
    environment:
      - node.name=elasticsearch
      - cluster.name=es-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms16g -Xmx16g"
      - ELASTIC_PASSWORD=changeme
      - xpack.security.enabled=true
      - xpack.security.authc.token.enabled=true      
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./config/elasticsearch.keystore:/usr/share/elasticsearch/config/elasticsearch.keystore
      - ./config/service_tokens:/usr/share/elasticsearch/config/service_tokens
      - esdata:/usr/share/elasticsearch/data
    networks:
      - proxy
  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    hostname: kibana
    restart: always
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_SERVICEACCOUNTTOKEN=<elasticsearch_serviceaccounttoken>
    ports:
      - 5601:5601
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - proxy
 
networks:
  proxy:
    internal: false
    name: proxy
volumes:
  esdata:
