---
version: "3"

services:
  nginx:
    image: openresty-lua
    container_name: openresty-lua
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - proxy
networks:
  proxy:
    internal: false
    name: proxy
